### ISSUE TITLE
fails to find flutter.h

### ISSUE THREAD

**Issue by gedw99** [bugsee/flutter-bugsee#1]
Issue:
I made a new project (flutter create" and copied your example code main.dart into it.

Env:
x-MacBook-Pro:opsharness apple$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.2.8, on Mac OS X 10.13.4 17E199, locale en-DE)
[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    ✗ Android license status unknown.
[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.22.2)
[✓] Connected devices (1 available)

````
x-MacBook-Pro:opsharness apple$ flutter run
Launching lib/main.dart on iPhone SE in debug mode...
Running Xcode clean...                                       1.2s
Starting Xcode build...
Xcode build done                                             1.7s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    === BUILD TARGET bugsee OF PROJECT Pods WITH CONFIGURATION Debug ===
    In file included from /Users/apple/.pub-cache/hosted/pub.dartlang.org/bugsee-1.0.2/ios/Classes/BugseePlugin.m:1:
    /Users/apple/.pub-cache/hosted/pub.dartlang.org/bugsee-1.0.2/ios/Classes/BugseePlugin.h:1:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
Could not build the application for the simulator.
Error launching application on iPhone SE.

````

**Comment by krassx** [comment]
Which CocoaPods version are you using? There known issues with 1.5+ and flutter. Here is the corresponding issue: https://github.com/flutter/flutter/issues/16036

**Comment by gedw99** [comment]
1.5.
- upgrading to Flutter Master fixed it as they suggested in the Flutter Issue your referenced.
Thansk for the quick feedback.
