### ISSUE TITLE
Android - Remove Notification bar reporting option

### ISSUE THREAD

**Issue by boaz-lachman** [bugsee/flutter-bugsee#10]
When installing the integrated bugsee app on android , a new notification is added to the notification tray. in the android sdk the is an option to remove this notification: https://docs.bugsee.com/sdk/android/configuration/ - NotificationBarTrigger

However, that is not an accessible option in the flutter SDK.

Can it please be added to the flutter config?

**Comment by krassx** [comment]
Hi @boaz-lachman, we've pushed the new version (1.3.1) where we added that missing flag. Please update to it and let us know how it goes.

**Comment by boaz-lachman** [comment]
@krassx galdly, how do I access this flag?

**Comment by boaz-lachman** [comment]
@krassx  found it , it works great

Thank you very much
