### ISSUE TITLE
Error received when compiling ipa for App Store

### ISSUE THREAD

**Issue by albertocappellina** [bugsee/flutter-bugsee#11]
Hi,
  
   when i try to build app for App Store, when uploading/validating app i received this error:

App Store Connect Operation Error
Invalid Signature. Code object is not signed at all. The file at path [Runner.app/Frameworks/Bugsee.framework/Tools/BugseeAgent] is not properly signed. Make sure you have signed your application with a distribution certificate, not an ad hoc certificate or a development certificate. Verify that the code signing settings in Xcode are correct at the target level (which override any values at the project level). Additionally, make sure the bundle you are uploading was built using a Release target in Xcode, not a Simulator target. If you are certain your code signing settings are correct, choose "Clean All" in Xcode, delete the "build" directory in the Finder, and rebuild your release target. For more information, please consult https://developer.apple.com/library/ios/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html

I started seeing this after latest update of bugsee. How can i fix ?

Thanks,
A

Here's my flutter doctor:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6 20G165 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.63.2)
[✓] Connected device (2 available)

**Comment by krassx** [comment]
Hi. You need to add an extra cleanup step to your iOS project. Please, follow instructions provided here: [https://docs.bugsee.com/sdk/ios/installation/#publishing-to-app-store-only-for-v120-and-later](https://docs.bugsee.com/sdk/ios/installation/#publishing-to-app-store-only-for-v120-and-later).

**Comment by albertocappellina** [comment]
Hi @krassx,

   thanks a lot, issue is resolved!

Take care
A
