### ISSUE TITLE
Support flutter 3.0

### ISSUE THREAD

**Issue by neiljaywarner** [bugsee/flutter-bugsee#13]
getting errors started with 'BugseeHttpClient' is missing implementations for these members:
 when trying to use Flutter 3.0 which is now in stable.

**Comment by krassx** [comment]
Hi Neil,

We have published the new version of Bugsee Flutter SDK (3.0.1) which supports Flutter 3 to pub.dev. You can find it here: https://pub.dev/packages/bugsee_flutter
