### ISSUE TITLE
App crashing in latest iOS v15.5 and Mac Monterey

### ISSUE THREAD

**Issue by nikunjkhunt-easternts** [bugsee/flutter-bugsee#14]
thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x18)
  frame #0: 0x00000001f10662e4 libsystem_pthread.dylib`pthread_mutex_lock + 12
libsystem_pthread.dylib`pthread_mutex_lock:
-> 0x1f10662e4 <+12>: ldr  x8, [x0]
  0x1f10662e8 <+16>: mov  w9, #0x545a
  0x1f10662ec <+20>: movk  w9, #0x4d55, lsl #16
  0x1f10662f0 <+24>: cmp  x8, x9
Target 0: (Runner) stopped.

**Comment by krassx** [comment]
Hi, we have checked and tested our SDK in the aforementioned configuration and found no issues (iPhone 13 with iOS 15.5, macOS Monterey 12.4 (21F79)).

Can you please make sure you're using the latest version of Bugsee SDK (note that new versions are now published to pub.dev: https://pub.dev/packages/bugsee_flutter)?

Unfortunately, provided stack trace does not give any hint about the potential culprit or the crash - any chance some other component or lib may be causing it?

**Comment by krassx** [comment]
No additional feedback received for a prolonged amount of time. Closing this issue for now.

If the problem still persists. Please, reach out with reopen request.
