### ISSUE TITLE
App not launching due to ARC Semantic Issue when launching on iOS

### ISSUE THREAD

**Issue by brandonrdgz** [bugsee/flutter-bugsee#16]
I get the following error when launching on iOS

Could not build the precompiled application for the device.
ARC Semantic Issue (Xcode): No known class method for selector 'logException:reason:options:'
/.pub-cache/hosted/pub.dev/bugsee_flutter-5.3.1/ios/Classes/BugseePlugin.m:276:16

ARC Semantic Issue (Xcode): No known class method for selector 'logUnhandledException:reason:'
/.pub-cache/hosted/pub.dev/bugsee_flutter-5.3.1/ios/Classes/BugseePlugin.m:280:16

Uncategorized (Xcode): Command SwiftCompile failed with a nonzero exit code

I'm using the following Flutter version

Flutter 3.13.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision efbf63d9c6 (24 hours ago) • 2023-08-15 21:05:06 -0500
Engine • revision 1ac611c64e
Tools • Dart 3.1.0 • DevTools 2.25.0

And I got no issues in flutter doctor.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.0, on macOS 13.4 22F66 darwin-arm64)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.2)
[✓] VS Code (version 1.79.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

**Comment by krassx** [comment]
This may happen because you need to force update the Bugsee pod. Please, try running

```
pod update Bugsee
```

in ```ios``` folder in your project

**Comment by brandonrdgz** [comment]
Tried just now. Didn't work

**Comment by krassx** [comment]
Can you please check which version of Bugsee pod is in the Podfile.lock?

**Comment by brandonrdgz** [comment]
Yes. This version:

Bugsee (3.7.1)

**Comment by krassx** [comment]
Ok, let me check this and get back with the results.

**Comment by krassx** [comment]
Indeed, there was an issue with these methods' signatures. We've pushed the update (5.3.2) which contains the fix for it. Please, try it and the issue should not appear any more.

**Comment by brandonrdgz** [comment]
The issue didn't appear any more. Thanks!!!

**Comment by krassx** [comment]
Great! Thank you for letting us know.

I am closing this issue as the problem was resolved.
