### ISSUE TITLE
clearAllAttributes takes a key parameter

### ISSUE THREAD

**Issue by koukibadr** [bugsee/flutter-bugsee#18]
I'm implementing clearAllAttributes and i've noticed that it takes a key as a parameter but in documentation it's called without params
```
// ... or clear all of them
Bugsee.clearAllAttributes();
```
here's the code from bugsee version 8.3.0
```
static Future<void> clearAllAttributes(String key) async {
    _init();
    await _channel?.invokeMethod('clearAllAttributes');
  }
```

**Comment by krassx** [comment]
Hi, indeed the redundant parameter is present there.

We have fixed that in 8.4.2

Thank you for pointing that out.
