### ISSUE TITLE
Doesn't work with flutter 2.5

### ISSUE THREAD

**Issue by neiljaywarner** [bugsee/flutter-bugsee#5]
gives ../../.pub-cache/git/flutter-bugsee-da8d2a4962502f2ab3c920781b8e836c590b0223/lib/src/networking.dart:219:32: Error: A value of type 'Future<bool> Function(Uri, String, String)?' can't be assigned to a variable of type 'Future<bool> Function(Uri, String, String?)?' because 'String?' is nullable and 'String' isn't.
 - 'Future' is from 'dart:async'.
 - 'Uri' is from 'dart:core'.
    _httpClient.authenticate = f;
                               ^
../../.pub-cache/git/flutter-bugsee-da8d2a4962502f2ab3c920781b8e836c590b0223/lib/src/networking.dart:226:37: Error: A value of type 'Future<bool> Function(String, int, String, String)?' can't be assigned to a variable of type 'Future<bool> Function(String, int, String, String?)?' because 'String?' is nullable and 'String' isn't.
 - 'Future' is from 'dart:async'.
    _httpClient.authenticateProxy = f;
                                    ^

see network_logging.dart in testfairy where they had the same thing
https://github.com/testfairy/testfairy-flutter/commit/a51a8c13645f2e8c9ea8cbd981dc88708972e00e

**Comment by neiljaywarner** [comment]
see https://github.com/bugsee/flutter-bugsee/pull/6

**Comment by krassx** [comment]
Fixed in [#6](https://github.com/bugsee/flutter-bugsee/pull/6)
