### ISSUE TITLE
Error while launcing Flutter application 

### ISSUE THREAD

**Issue by albertocappellina** [bugsee/flutter-bugsee#7]
Hi guys,

   as stated i'm receiving an error while launching flutter app with bugsee.

Here's the error log

` Error: The parameter 'f' of the method 'BugseeHttpClient.authenticate' has type 'Future<bool> Function(Uri, String, String?)?', which does not match the corresponding type, 'Future<bool> Function(Uri, String, String)?', in the overridden method, 'HttpClient.authenticate'.
 - 'Future' is from 'dart:async'.
 - 'Uri' is from 'dart:core'.
Change to a supertype of 'Future<bool> Function(Uri, String, String)?', or, for a covariant parameter, a subtype.
      Future<bool> Function(Uri url, String scheme, String? realm)? f) {
                                                                    ^
org-dartlang-sdk:///third_party/dart/sdk/lib/_http/http.dart:1744:12: Context: This is the overridden method ('authenticate').
  void set authenticate(Future<bool> f(Uri url, String scheme, String realm)?);`

Could you please help?

Thanks,
Alberto

**Comment by krassx** [comment]
You're welcome!
